# encoding: utf-8
from __future__ import unicode_literals


pt = {
    'Амстердам': 'Amsterdam',
    'Берлин': 'Berlin',
    'Брюссель': 'Brussel',
    'Будапеща': 'Budapest',
    'Бялисток': 'Białystok',
    'Варна': 'Варна',
    'Варшава': 'Warsaw',
    'Вилнюс': 'Vilnius',
    'Вильнюс': 'Vilnius',
    'Винница': 'Vinnytsia',
    'Витебск': 'Vitebsk',
    'Гданьск': 'Gdansk',
    'Гомель': 'Gomel',
    'Гродно': 'Hrodna',
    'Дюссельдорф': 'Dusseldorf',
    'Калининград': 'Kaliningrad',
    'Киев': 'Kiev',
    'Краков': 'Krakow',
    'Каунас': 'Kaunas',
    'Львов': 'Lviv',
    'Люблин', 'Lublin',
    'Минск': 'Minsk',
    'Мозырь': 'Mazyr',
    'Москва': 'Moscow',
    'Могилев': 'Mogilev',
    'Мюнхен': 'Munich',
    'Одесса': 'Odessa',
    'Одеса': 'Odessa',
    'Орша': 'Orsha',
    'Париж': 'Paris',
    'Прага': 'Prague',
    'Рига': 'Riga',
    'Санкт-Петербург': 'St.Petersburg',
    'София': 'Sofia',
    'Таллин': 'Tallinn',
    'Таллинн': 'Tallinn',
    'Тернополь': 'Ternopil',
    'Трускавец': 'Truskavets',
    'Умань': 'Uman',
    'Франкфурт': 'Frankfurt',
    'Хмельницкий': 'Khmelnytskyi',
}
